name: 'Check if version bumped'
description: 'Checks if version is bumped in package.json in pull requests'
inputs:
  token:
    description: 'Token to use to retrieve base file. Needed only on private repositories'
    required: false
    default: ''
  path:
    description: 'Relative path to package.json file. Do not start with /'
    required: false
    default: 'package.json'
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: info
  color: yellow
